/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./public/**/*.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        karla: ["Karla", "sans-serif"],
        fira: ["Fira Mono", "space"],
        roboto: ["Roboto Mono", "monospace"],
        noto: ["Noto Sans Mono", "monospace"],
        ibm: ["IBM Plex Mono", "monospace"],
        majormono: ["Major Mono Display", "monospace"],
        jetbrains: ["JetBrains Mono", "monospace"],
        bungee: ["Bungee Hairline", "monospace"],
      },
      keyframes: {
        fadeout: {
          "0%": { transform: "scale(1)", width: "18rem" },
          "5%": { transform: "scale(0.95)", width: "17rem" },
          "10%": { transform: "scale(0.9)", width: "16rem" },
          "15%": { transform: "scale(0.85)", width: "15rem" },
          "20%": { transform: "scale(0.8)", width: "14rem" },
          "25%": { transform: "scale(0.75)", width: "13rem" },
          "30%": { transform: "scale(0.7)", width: "12rem" },
          "35%": { transform: "scale(0.65)", width: "11rem" },
          "40%": { transform: "scale(0.6)", width: "10rem" },
          "45%": { transform: "scale(0.55)", width: "9rem" },
          "50%": { transform: "scale(0.5)", width: "8rem" },
          "55%": { transform: "scale(0.45)", width: "7rem" },
          "60%": { transform: "scale(0.4)", width: "6rem" },
          "65%": { transform: "scale(0.35)", width: "5rem" },
          "70%": { transform: "scale(0.3)", width: "4rem" },
          "75%": { transform: "scale(0.25)", width: "3rem" },
          "80%": { transform: "scale(0.2)", width: "2rem" },
          "85%": { transform: "scale(0.15)", width: "1rem" },
          "90%": { transform: "scale(0.1)", width: "0.5rem" },
          "95%": { transform: "scale(0.05)", width: ".25rem" },
          "100%": { transform: "scale(0)", width: "0rem" },
        },
        fadein: {
          "0%": { transform: "scale(0)", width: "0rem" },
          "5%": { transform: "scale(0.05)", width: "0.25rem" },
          "10%": { transform: "scale(0.1)", width: "0.5rem" },
          "15%": { transform: "scale(0.15)", width: "1rem" },
          "20%": { transform: "scale(0.2)", width: "2rem" },
          "25%": { transform: "scale(0.25)", width: "3rem" },
          "30%": { transform: "scale(0.3)", width: "4rem" },
          "35%": { transform: "scale(0.35)", width: "5rem" },
          "40%": { transform: "scale(0.4)", width: "6rem" },
          "45%": { transform: "scale(0.45)", width: "7rem" },
          "50%": { transform: "scale(0.5)", width: "8rem" },
          "55%": { transform: "scale(0.55)", width: "9rem" },
          "60%": { transform: "scale(0.6)", width: "10rem" },
          "65%": { transform: "scale(0.65)", width: "11rem" },
          "70%": { transform: "scale(0.7)", width: "12rem" },
          "75%": { transform: "scale(0.75)", width: "13rem" },
          "80%": { transform: "scale(0.8)", width: "14rem" },
          "85%": { transform: "scale(0.85)", width: "15rem" },
          "90%": { transform: "scale(0.9)", width: "16rem" },
          "95%": { transform: "scale(0.95)", width: "17rem" },
          "100%": { transform: "scale(1)", width: "18rem" },
        },
      },
      animation: {
        "fade-out": "fadeout 1s linear",
        "fade-in": "fadein 1s linear",
      },
    },
    colors: {
      "dark-navy": "#020c1b",
      navy: "#0a192f",
      "light-navy": "#112240",
      "lightest-navy": "#233554",
      "dark-slate": "#495670",
      slate: "#8892b0",
      "light-slate": "#a8b2d1",
      "lightest-slate": "#ccd6f6",
      white: "#e6f1ff",
      green: "#47b8a5",
      pink: "#f57dff",
      blue: "#57cbff",
    },
    borderWidth: {
      DEFAULT: "1px",
      0: "0",
      1: "1px",
      2: "2px",
      3: "3px",
      4: "4px",
      6: "6px",
      8: "8px",
    },
  },
  plugins: [require("tailwind-scrollbar-hide")],
};
